### PR TITLE
How to compile update

### PR DESCRIPTION
**Pull request by RudaF**
Issue done in order to learn how to pull request.

### CODE REVIEW

**Comment by Kazuo256** [comment]
@henriquegemignani 
Since when do we use appveyor? How can we configure it? XD

**Comment by henriquegemignani** [comment]
Wow, I tried setting it up sometime in the past, but gave up trying to figure out how to use CMake with it.

**Comment by Kazuo256** [comment]
So we just disable the hook?

**Comment by henriquegemignani** [comment]
Actually, looking at the build log, it appears the build genuinely failed! I've tried the same here, and it also fails. Apparently, UGDK_CREATE_BINDINGS being ON, but having no swig installed causes an error.

**Comment by Kazuo256** [comment]
Which means it must also have been broken before. Should we ignore it, then? Or fix the dev branch, then rebase this?

**Comment by henriquegemignani** [comment]
Your choice.

**Pull request merged**
